/* Build DTCG tokens -> build/variables.css with Style Dictionary (v4).
   Output: one CSS file with the default :root block plus two motion-personality
   override blocks ([data-motion="calm"|"lively"], durations only).
   Demos inline a copy of build/variables.css so they open without a build. */
import StyleDictionary from "style-dictionary";
import { promises as fs } from "node:fs";

const BASE = ["shared/tokens/primitive.tokens.json", "shared/tokens/semantic.tokens.json"];
const TMP = "build/.tmp";
const CSS_TRANSFORMS = ["attribute/cti", "name/kebab", "color/css", "cubicBezier/css"];

async function buildBlock(source, selector, filter) {
  const sd = new StyleDictionary({
    source,
    platforms: {
      css: {
        transforms: CSS_TRANSFORMS,
        buildPath: TMP + "/",
        files: [{
          destination: "block.css",
          format: "css/variables",
          ...(filter ? { filter } : {}),
          options: { outputReferences: true, selector }
        }]
      }
    },
    log: { verbosity: "silent" }
  });
  await sd.buildAllPlatforms();
  const css = await fs.readFile(TMP + "/block.css", "utf8");
  // drop Style Dictionary's auto header comment; keep just the selector block
  return css.replace(/\/\*[\s\S]*?\*\/\s*/, "").trim();
}

const onlyDuration = (t) => t.path[0] === "duration";

const root   = await buildBlock(BASE, ":root");
const calm   = await buildBlock([...BASE, "shared/tokens/motion/calm.tokens.json"],   ':root[data-motion="calm"]',   onlyDuration);
const lively = await buildBlock([...BASE, "shared/tokens/motion/lively.tokens.json"], ':root[data-motion="lively"]', onlyDuration);

const header = "/* Generated by Style Dictionary — do not edit by hand.\n" +
               "   Source: shared/tokens/*.tokens.json   ·   npm run build:tokens\n" +
               "   Motion personalities: default :root, plus [data-motion=\"calm\"|\"lively\"]. */\n\n";

await fs.mkdir("build", { recursive: true });
await fs.writeFile("build/variables.css", header + root + "\n\n" + calm + "\n\n" + lively + "\n", "utf8");
await fs.rm(TMP, { recursive: true, force: true });
console.log("Wrote build/variables.css");
